name: docker-build-and-push

# run only when PR to master was closed
on:
  pull_request:
    branches: 
      - main
    types: [closed]

jobs:
  docker-build-and-push:
    # only if the PR was closed due to merging
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: flask-web-app:${{ github.run_number }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}