name: docker-build-and-push

on:
  push:
  # Only on pushes to main branch
    branches:
      - main
    # Only trigger on merges to main
    paths-ignore:
      - '**'

jobs:
  docker-build-and-push:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: flask-web-app:${{ github.run_number }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}